//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipExtractor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZipExtractor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _9054803 {
            get {
                object obj = ResourceManager.GetObject("9054803", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage bo_country_v92 {
            get {
                object obj = ResourceManager.GetObject("bo_country_v92", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 提取{0} 的本地化字符串。
        /// </summary>
        internal static string CurrentFileExtracting {
            get {
                return ResourceManager.GetString("CurrentFileExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage enableclustering {
            get {
                object obj = ResourceManager.GetObject("enableclustering", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 无法更新文件！ 的本地化字符串。
        /// </summary>
        internal static string FileStillInUseCaption {
            get {
                return ResourceManager.GetString("FileStillInUseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}仍处于打开状态，并且正在使用&quot;{1}&quot;。请手动关闭进程并按重试。 的本地化字符串。
        /// </summary>
        internal static string FileStillInUseMessage {
            get {
                return ResourceManager.GetString("FileStillInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 {0} 的本地化字符串。
        /// </summary>
        internal static string Removing {
            get {
                return ResourceManager.GetString("Removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待应用程序退出... 的本地化字符串。
        /// </summary>
        internal static string WaitingForAppToExitMessage {
            get {
                return ResourceManager.GetString("WaitingForAppToExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ZipExtractor {
            get {
                object obj = ResourceManager.GetObject("ZipExtractor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
